### ISSUE TITLE
Aren't you satisfied? Spelling mistakes in description.

### ISSUE THREAD

**Issue by Melvin-Tan** [Wishes-CS3216/Wishes-Frontend#18]
Title: """I'm not satisfied :("""
Body: """Clicking 'Continue' will cause both the helper and yourself to not gain any bonus points. If you do appreciate the help provided, be satisfied and click 'Cancel' instead? :)"""

Idk, but right now the that portion has a lot of spelling and grammar mistake so consider using this version? :P

**Comment by fischsux** [comment]
done
