### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Melvin-Tan** [Wishes-CS3216/Wishes-Frontend#19]
Check through all 3 tables (+ user's rank)

1) When value is 1, make sure it is singular (1 wish, not 1 wishes, 1 help not 1 helps)

2) When value is 0, make sure it is rendered (I didn't try this, but yesterday it just shows wishes instead of 0 wishes). For zero, keep it plural (it's correct, no need to change anything).

**Comment by fischsux** [comment]
Put it in this way: 2 helps, 1 help, no helps. Done & Deployed
